### ISSUE TITLE
Tarball missing directory

### ISSUE THREAD

**Issue by craiglund** [browndeer/coprthr#4]
I've just tried to install the Parallella version of 1.5.0 from the tarball on your website. The install script expects a directory named "icd" in the distribution. That directory was not included.

**Comment by browndeer** [comment]
Craig, thank you for reporting this issue - yes, you are correct, that directory seems to have been deleted when the build was packaged.  We will make sure to correct this.

-DAR

**Comment by browndeer** [comment]
This issue has been resolved in an updated package available from the download page.
