### ISSUE TITLE
Parallella install.txt

### ISSUE THREAD

**Issue by craiglund** [browndeer/coprthr#6]
It would be useful if your install document for Parallella noted that you can't just type "gmake quicktest". You must first issue the following lines:

sudo ln -s /usr/bin/make /usr/bin/gmake
sudo apt-get install libelf1 libelfg0 libconfig9

In a separate issue I talk about the fact that the install of libconfig9 will fail.

**Comment by browndeer** [comment]
Craig,

Here is a link to the Parallella Quick Start Guide:
http://www.browndeertechnology.com/docs/Parallella_quick_start_guide.pdf

The instructions differ slightly from those found in the document you referenced.  Sorry for the confusion.

Also, please note that yesterday we determined that the image on recently shipped boards difers from that on our prototype which we received in December and used to build and test the COPRTHR SDK package that was posted.  We identified several path and naming issues that will cause problems, and we are working to get an updated image so we can re-build the package as soon as possible.  We hope to complete this within 24-48 hours.

I appologize for any inconvenience this may cause.  Please feel free to email support@browndeertechnology.com if you have any questons about this.

-DAR

**Comment by browndeer** [comment]
The gmake issue should be fixed for pre-built package and builds from source.  This is now addressed by the configure script.

PLEASE NOTE that you MUST install libelf-0.8.13.  We have tried using default libelf-1.x branch several times over the last two years, and it _always_ fails to support the required functionality.

Updated package and instructions can be found on the download page or built from source by downloading v1.5.0-rc2 from github.  This has been tested using the latest Parallella image.

-DAR
